/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.frms;


import java.util.Date;
import java.text.SimpleDateFormat;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import main.clases.HashSalt;
import main.clases.PasswordUtil;
import main.controladores.BglTbUsuarioJpaController;
import main.controladores.exceptions.NonexistentEntityException;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import main.entidades.BglTbUsuario;

/**
 *
 * @author michael.beltran
 */
public class ifrmLogin extends javax.swing.JInternalFrame {

    ///Declaracion Variables globales
    public frmMain main;
    public EntityManagerFactory factory;
    private BglTbUsuario usuario;      
    
    private final static Logger log=Logger.getLogger(ifrmLogin.class);
    ///Fin declaracion variables globales
    
    /**
     * Creates new form ifrmLogin
     * @param factory
     * @param frm
     */
    public ifrmLogin(EntityManagerFactory factory,frmMain frm) {
        initComponents();
        PropertyConfigurator.configure("log4j.properties");
        this.factory=factory;
        this.main=frm;
    }

    private String[] encriptarClavePKSC5(String userPassword){
        String[] passwordEncriptado = new String[2];
        try{
            
        HashSalt hs = PasswordUtil.getHash(userPassword);
	
        
	passwordEncriptado[0]=hs.getHash();
        passwordEncriptado[1]=hs.getSalt();
        
	boolean isValid = PasswordUtil.ValidatePass(userPassword, hs.getHash(), hs.getSalt());
	System.out.println(isValid ? "válida" : "no válida"); // no válida
        
        }
        catch(Exception e){e.printStackTrace();}
        
        return passwordEncriptado;
    }
    
    private void conectar()
    {
        
        String user=this.jtf_usuario.getText();
        String pass=this.jpf_password.getText();

        if(user.equals("")||pass.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Debe llenar todos los campos");
            return;
        }
  
        try{
            
            String[] password=this.encriptarClavePKSC5(pass);
            System.out.println(password[0]); 
            System.out.println(password[1]); 
            String hash=password[0];
            String salt=password[1];
            
        //validar usuario y contraseña
        BglTbUsuarioJpaController usuarioJpa=new BglTbUsuarioJpaController(this.factory);
        this.usuario=usuarioJpa.findBglTbUsuario(user,hash);

            if(this.usuario!=null)
            {
                //actualizar a ultima fecha de acceso y porcion salt del hash
                String hora=String.format("%tT", new java.util.Date());
                String fecha=String.format("%tF", new java.util.Date());
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Date fecUlt=formatter.parse(fecha+" "+hora);
                usuario.setUsuFeculting(fecUlt);
                usuario.setUsuSalt(salt);
                usuarioJpa.edit(usuario);
                
                JOptionPane.showMessageDialog(this,"Conexión Exitosa");
                main.usuarioSesion=this.usuario;
                main.verDatosUsuarioSesion();
                
                //deshabilitar botón de inicio de sesión
                main.deshabilitarItemIniciarSesion();
                
                //habilitar cerrar sesion
                main.habilitarItemCerrarSesion();
                
                //cerrar esta ventana
                this.dispose();
                main.frmLogin=null;
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Conexión Fallida");
            }
        }
        catch(Exception e){
            
            JOptionPane.showMessageDialog(this,"Usuario o contraseña incorrecta");
            System.out.println("Ha ocurrido un error: "+e.getMessage());
        }
        finally
        {
            log.info("Finalizando método btnConectarActionPerformed");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnSalir = new javax.swing.JButton();
        jtf_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnConectar = new javax.swing.JButton();
        jlbImagen = new javax.swing.JLabel();
        jpf_password = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(15, 35, 53));
        setClosable(true);
        setTitle("Login");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/16x16-png-exit.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario");

        jbtnSalir.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jbtnSalir.setText("Salir");
        jbtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalirActionPerformed(evt);
            }
        });

        jtf_usuario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jtf_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_usuarioKeyPressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");

        jbtnConectar.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jbtnConectar.setText("Conectar");
        jbtnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConectarActionPerformed(evt);
            }
        });

        jlbImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/ingreso.png"))); // NOI18N
        jlbImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpf_password.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jpf_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpf_passwordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jbtnConectar)
                .addGap(3, 3, 3)
                .addComponent(jbtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(106, 106, 106))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jlbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1))
                        .addComponent(jLabel2))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jpf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnConectar)
                    .addComponent(jbtnSalir))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(16, 16, 16)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jpf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(0, 45, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalirActionPerformed
        // TODO add your handling code here:
        this.main.frmLogin=null;
        this.dispose();
    }//GEN-LAST:event_jbtnSalirActionPerformed

    private void jbtnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConectarActionPerformed
        // TODO add your handling code here:
        conectar();
    }//GEN-LAST:event_jbtnConectarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        
        this.main.frmLogin=null;
        
    }//GEN-LAST:event_formInternalFrameClosing

    private void jpf_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpf_passwordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
        {
            conectar();
        }
        
    }//GEN-LAST:event_jpf_passwordKeyPressed

    private void jtf_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_usuarioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()==10)
        {
            conectar();
        }
    }//GEN-LAST:event_jtf_usuarioKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtnConectar;
    private javax.swing.JButton jbtnSalir;
    private javax.swing.JLabel jlbImagen;
    private javax.swing.JPasswordField jpf_password;
    private javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables
}
