
package main.frms;

/**
 *
 * @author michael.beltran
 */
public class ifrmRegistroAtenciones extends javax.swing.JInternalFrame {

    /**
     * crea un nuevo formulario de Registro de Atenciones
     */
    public ifrmRegistroAtenciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAcciones = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCiudad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbSector = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbTipoEmergencia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbCatalogoEmergencia = new javax.swing.JComboBox<>();
        dcFechaInic = new com.toedter.calendar.JDateChooser();
        dcFechaFin = new com.toedter.calendar.JDateChooser();
        jbtnFiltrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtAliasUsuario = new javax.swing.JTextField();
        jbtnNoFiltrar = new javax.swing.JButton();
        jpListadoEmergencias = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtEmergencias = new javax.swing.JTable();

        setBackground(new java.awt.Color(15, 35, 53));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registro y Consulta Atenciones de Emergencias");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/16x16-png-antena.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpAcciones.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtros de búsqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jpAcciones.setOpaque(false);
        jpAcciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("al");
        jpAcciones.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 20, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ciudad");
        jLabel2.setToolTipText("");
        jpAcciones.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cbCiudad.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jpAcciones.add(cbCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 150, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha Incidente");
        jpAcciones.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sector");
        jLabel4.setToolTipText("");
        jpAcciones.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        cbSector.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jpAcciones.add(cbSector, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 150, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo Emergencia");
        jLabel5.setToolTipText("");
        jpAcciones.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        cbTipoEmergencia.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jpAcciones.add(cbTipoEmergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 190, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Atendido por:");
        jLabel6.setToolTipText("");
        jpAcciones.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 90, 20));

        cbEstado.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jpAcciones.add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 140, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Catalogo");
        jpAcciones.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jpAcciones.add(cbCatalogoEmergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 210, -1));

        dcFechaInic.setDateFormatString("yyyy-MMM-dd");
        jpAcciones.add(dcFechaInic, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 110, -1));

        dcFechaFin.setDateFormatString("yyyy-MMM-dd");
        jpAcciones.add(dcFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 20, 120, -1));

        jbtnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/16x16-filter-icon.png"))); // NOI18N
        jbtnFiltrar.setText("Filtrar");
        jpAcciones.add(jbtnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado de la emergencia:");
        jLabel8.setToolTipText("");
        jpAcciones.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 170, 20));
        jpAcciones.add(jtxtAliasUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 120, -1));

        jbtnNoFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/16x16-filter-icon.png"))); // NOI18N
        jbtnNoFiltrar.setText("No filtrar");
        jpAcciones.add(jbtnNoFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, -1));

        getContentPane().add(jpAcciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 650, 139));

        jpListadoEmergencias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eventos de emergencias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jpListadoEmergencias.setOpaque(false);
        jpListadoEmergencias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtEmergencias.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jtEmergencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtEmergencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEmergenciasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtEmergencias);

        jpListadoEmergencias.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 20, 640, 150));

        getContentPane().add(jpListadoEmergencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtEmergenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEmergenciasMouseClicked
        
    }//GEN-LAST:event_jtEmergenciasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCatalogoEmergencia;
    private javax.swing.JComboBox<String> cbCiudad;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbSector;
    private javax.swing.JComboBox<String> cbTipoEmergencia;
    private com.toedter.calendar.JDateChooser dcFechaFin;
    private com.toedter.calendar.JDateChooser dcFechaInic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnFiltrar;
    private javax.swing.JButton jbtnNoFiltrar;
    private javax.swing.JPanel jpAcciones;
    private javax.swing.JPanel jpListadoEmergencias;
    private javax.swing.JTable jtEmergencias;
    private javax.swing.JTextField jtxtAliasUsuario;
    // End of variables declaration//GEN-END:variables
}
