/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.frms;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author michael.beltran
 */
public class ifrmAbout extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmAbout
     */
    public ifrmAbout() {
        initComponents();
        
    }

    public void renderizarLogos()
    {
        try
        {
        
        ImageIcon img=new ImageIcon("src/main/img/ug-logo.png");
        Icon icon=new ImageIcon(img.getImage().getScaledInstance(jlbLogoUniversidad.getWidth(),jlbLogoUniversidad.getHeight() , Image.SCALE_DEFAULT));
        jlbLogoUniversidad.setIcon(icon);
        
        img=new ImageIcon("src/main/img/facultad.png");
        icon=new ImageIcon(img.getImage().getScaledInstance(jlbLogoFacultad.getWidth(),jlbLogoFacultad.getHeight() , Image.SCALE_DEFAULT));
        jlbLogoFacultad.setIcon(icon);
        
        img=new ImageIcon("src/main/img/logocisc.jpg");
        icon=new ImageIcon(img.getImage().getScaledInstance(jlbLogoCarrera.getWidth(),jlbLogoCarrera.getHeight() , Image.SCALE_DEFAULT));
        jlbLogoCarrera.setIcon(icon);

        this.repaint();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this,"Error al renderizar logos");
            System.out.println("Error al renderizar logos: "+ex.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbLogoUniversidad = new javax.swing.JLabel();
        jlbLogoFacultad = new javax.swing.JLabel();
        jlbLogoCarrera = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtDescripcion = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(15, 35, 53));
        setClosable(true);
        setIconifiable(true);
        setTitle("About OpenBengalas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/16x16-png-antena.png"))); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbLogoUniversidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/ug-logo.png"))); // NOI18N
        jlbLogoUniversidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jlbLogoUniversidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 70, 70));

        jlbLogoFacultad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/facultad.png"))); // NOI18N
        jlbLogoFacultad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jlbLogoFacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 210, 70));

        jlbLogoCarrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/logocisc.jpg"))); // NOI18N
        jlbLogoCarrera.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jlbLogoCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 80, 70));

        jtxtDescripcion.setEditable(false);
        jtxtDescripcion.setBackground(new java.awt.Color(15, 35, 53));
        jtxtDescripcion.setColumns(20);
        jtxtDescripcion.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jtxtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jtxtDescripcion.setLineWrap(true);
        jtxtDescripcion.setRows(5);
        jtxtDescripcion.setText("\t\tUNIVERSIDAD DE GUAYAQUIL\n\tFACULTAD DE CIENCIAS MATEMATICAS Y FÍSICAS\n\tCARRERA DE INGENIERÍA EN SISTEMAS COMPUTACIONALES\n\n\t\tPROYECTO DE TITULACIÓN\n\tDESARROLLO DE APP PILOTO PARA REGISTRO Y\n\t        MONITOREO DE EVENTOS EMERGENCIAS \n\t\tEN PARQUES DE GUAYAQUIL\n\n\t\tDESARROLLADO POR:\n\t\tMICHAEL BELTRÁN B.\n\n\t\t           TUTOR:\n\t        \tING. FERNANDO CASTRO A.\n\n\t\t           REVISOR:\n\t\tING. JENIFFER BONILLA B.\n\n\t\tPERÍODO LECTIVO:\n\t\t     2017-2018");
        jtxtDescripcion.setToolTipText("");
        jtxtDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jtxtDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 470, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbLogoCarrera;
    private javax.swing.JLabel jlbLogoFacultad;
    private javax.swing.JLabel jlbLogoUniversidad;
    private javax.swing.JTextArea jtxtDescripcion;
    // End of variables declaration//GEN-END:variables
}
