/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.frms;

/**
 *
 * @author michael.beltran
 */
public class ifrmEspera extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmEspera
     * @param frame
     */
    public ifrmEspera(javax.swing.JFrame frame) {
        initComponents();
        this.setLocation((frame.getWidth()/2), (frame.getHeight()/2));
    }

    
    public void setMensaje(String mensaje)
    {
        this.jlbMensaje.setText(mensaje);
        this.jlbMensaje.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbGif = new javax.swing.JLabel();
        jlbMensaje = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Espera...");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/16x16-png-antena.png"))); // NOI18N
        setVisible(true);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jlbGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/25x25-gif-load.gif"))); // NOI18N
        getContentPane().add(jlbGif);

        jlbMensaje.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jlbMensaje.setText("Cargando datos...");
        getContentPane().add(jlbMensaje);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbGif;
    private javax.swing.JLabel jlbMensaje;
    // End of variables declaration//GEN-END:variables
}
