/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.frms;

/**
 *
 * @author michael.beltran
 */
public class jdialEspera extends javax.swing.JDialog {

    /**
     * Creates new form jdialEspera
     */
    public jdialEspera(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocation((parent.getWidth()/2), (parent.getHeight()/2));
        initComponents();
    }
    
    public void setMensaje(String mensaje)
    {
        this.jlbMensaje.setText(mensaje);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbGif = new javax.swing.JLabel();
        jlbMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        setModalityType(java.awt.Dialog.ModalityType.TOOLKIT_MODAL);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jlbGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/25x25-gif-load.gif"))); // NOI18N
        getContentPane().add(jlbGif);

        jlbMensaje.setText("Cargando datos...");
        getContentPane().add(jlbMensaje);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jlbGif;
    public javax.swing.JLabel jlbMensaje;
    // End of variables declaration//GEN-END:variables
}
