/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.frms;

/**
 *
 * @author michael.beltran
 */
public class jpanelEspera extends javax.swing.JPanel {

    /**
     * Creates new form jpanelEspera
     */
    public jpanelEspera() {
        this.setLocation(550, 250);
        initComponents();
        
    }

    
    public void setMensaje(String mensaje)
    {
        this.jlbMensaje.setText(mensaje);
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbGif = new javax.swing.JLabel();
        jlbMensaje = new javax.swing.JLabel();

        jlbGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/img/25x25-gif-load.gif"))); // NOI18N

        jlbMensaje.setText("Cargando datos...");
        jlbMensaje.setFocusable(false);
        jlbMensaje.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(jlbGif)
                    .addGap(5, 5, 5)
                    .addComponent(jlbMensaje)
                    .addGap(0, 79, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbGif)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jlbMensaje)))
                    .addGap(0, 19, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbGif;
    private javax.swing.JLabel jlbMensaje;
    // End of variables declaration//GEN-END:variables
}
